/*
 *   Sqriptor text editor for Qt5
 *   Copyright 2025 by Thomas Lübking <thomas.luebking@gmail.com>
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License version 2
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details
 *
 *   You should have received a copy of the GNU General Public
 *   License along with this program; if not, write to the
 *   Free Software Foundation, Inc.,
 *   51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/


#include "lexer/qtpro.h"
//#include <QtDebug>

QsciLexerQtPro::QsciLexerQtPro(QObject *parent) : QsciLexerBash(parent)
{
}


const char *QsciLexerQtPro::keywords(int set) const
{
//    qDebug() << "queried set" << set;
    if (set == 1) return
        "ANDROID_ABIS ANDROID_API_VERSION ANDROID_APPLICATION_ARGUMENTS ANDROID_BUNDLED_JAR_DEPENDENCIES "
        "ANDROID_DEPLOYMENT_DEPENDENCIES ANDROID_DEPLOYMENT_SETTINGS_FILE ANDROID_EXTRA_LIBS ANDROID_EXTRA_PLUGINS "
        "ANDROID_FEATURES ANDROID_LIB_DEPENDENCIES ANDROID_MIN_SDK_VERSION ANDROID_PACKAGE_SOURCE_DIR "
        "ANDROID_PERMISSIONS ANDROID_TARGET_SDK_VERSION ANDROID_VERSION_CODE ANDROID_VERSION_NAME CONFIG "
        "DEFINES DEFINES_DEBUG DEFINES_RELEASE DEF_FILE DEPENDPATH DESTDIR DISTFILES DLLDESTDIR EXTRA_TRANSLATIONS "
        "FORMS GUID HEADERS ICON IDLSOURCES INCLUDEPATH INSTALLS JAVA_HOME LEXIMPLS LEXOBJECTS LEXSOURCES "
        "LIBS LIBS_PRIVATE LITERAL_HASH MAKEFILE MAKEFILE_GENERATOR MSVCPROJ_* MOC_DIR OBJECTIVE_HEADERS "
        "OBJECTIVE_SOURCES OBJECTS OBJECTS_DIR POST_TARGETDEPS PRE_TARGETDEPS PRECOMPILED_HEADER PWD OUT_PWD "
        "QM_FILES_RESOURCE_PREFIX QM_FILES_INSTALL_PATH QML_IMPORT_PATH QMLPATHS QMAKE QMAKESPEC QMAKE_APPLE_DEVICE_ARCHS "
        "QMAKE_AR_CMD QMAKE_BUNDLE_DATA QMAKE_BUNDLE_EXTENSION QMAKE_CC QMAKE_CFLAGS QMAKE_CFLAGS_DEBUG QMAKE_CFLAGS_RELEASE "
        "QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO QMAKE_CFLAGS_SHLIB QMAKE_CFLAGS_THREAD QMAKE_CFLAGS_WARN_OFF "
        "QMAKE_CFLAGS_WARN_ON QMAKE_CLEAN QMAKE_CXX QMAKE_CXXFLAGS QMAKE_CXXFLAGS_DEBUG QMAKE_CXXFLAGS_RELEASE "
        "QMAKE_CXXFLAGS_RELEASE_WITH_DEBUGINFO QMAKE_CXXFLAGS_SHLIB QMAKE_CXXFLAGS_THREAD QMAKE_CXXFLAGS_WARN_OFF "
        "QMAKE_CXXFLAGS_WARN_ON QMAKE_DEVELOPMENT_TEAM QMAKE_DISTCLEAN QMAKE_EXTENSION_SHLIB QMAKE_EXTENSION_STATICLIB "
        "QMAKE_EXT_MOC QMAKE_EXT_UI QMAKE_EXT_PRL QMAKE_EXT_LEX QMAKE_EXT_YACC QMAKE_EXT_OBJ QMAKE_EXT_CPP "
        "QMAKE_EXT_H QMAKE_EXTRA_COMPILERS QMAKE_EXTRA_TARGETS QMAKE_FAILED_REQUIREMENTS QMAKE_FRAMEWORK_BUNDLE_NAME "
        "QMAKE_FRAMEWORK_VERSION QMAKE_HOST QMAKE_INCDIR QMAKE_INCDIR_EGL QMAKE_INCDIR_OPENGL QMAKE_INCDIR_OPENGL_ES2 "
        "QMAKE_INCDIR_OPENVG QMAKE_INCDIR_X11 QMAKE_INFO_PLIST QMAKE_IOS_DEPLOYMENT_TARGET QMAKE_IOS_LAUNCH_SCREEN "
        "QMAKE_LFLAGS QMAKE_LFLAGS_CONSOLE QMAKE_LFLAGS_DEBUG QMAKE_LFLAGS_PLUGIN QMAKE_LFLAGS_RPATH QMAKE_LFLAGS_REL_RPATH "
        "QMAKE_REL_RPATH_BASE QMAKE_LFLAGS_RPATHLINK QMAKE_LFLAGS_RELEASE QMAKE_LFLAGS_RELEASE_WITH_DEBUGINFO "
        "QMAKE_LFLAGS_APP QMAKE_LFLAGS_SHLIB QMAKE_LFLAGS_SONAME QMAKE_LFLAGS_THREAD QMAKE_LFLAGS_WINDOWS "
        "QMAKE_LIBDIR QMAKE_LIBDIR_POST QMAKE_LIBDIR_FLAGS QMAKE_LIBDIR_EGL QMAKE_LIBDIR_OPENGL QMAKE_LIBDIR_OPENVG "
        "QMAKE_LIBDIR_X11 QMAKE_LIBS QMAKE_LIBS_PRIVATE QMAKE_LIBS_EGL QMAKE_LIBS_OPENGL QMAKE_LIBS_OPENGL_ES1 "
        "QMAKE_LIBS_OPENGL_ES2 QMAKE_LIBS_OPENVG QMAKE_LIBS_THREAD QMAKE_LIBS_X11 QMAKE_LIB_FLAG QMAKE_LINK "
        "QMAKE_LINK_SHLIB_CMD QMAKE_LN_SHLIB QMAKE_LRELEASE_FLAGS QMAKE_OBJECTIVE_CFLAGS QMAKE_POST_LINK QMAKE_PRE_LINK "
        "QMAKE_PROJECT_NAME QMAKE_PROVISIONING_PROFILE QMAKE_MAC_SDK QMAKE_MACOSX_DEPLOYMENT_TARGET QMAKE_MAKEFILE "
        "QMAKE_QMAKE QMAKE_RESOURCE_FLAGS QMAKE_RPATHDIR QMAKE_RPATHLINKDIR QMAKE_RUN_CC QMAKE_RUN_CC_IMP "
        "QMAKE_RUN_CXX QMAKE_RUN_CXX_IMP QMAKE_SONAME_PREFIX QMAKE_TARGET QMAKE_TARGET_COMPANY QMAKE_TARGET_DESCRIPTION"
        "QMAKE_TARGET_COPYRIGHT QMAKE_TARGET_PRODUCT QMAKE_TARGET_ORIGINAL_FILENAME QMAKE_TARGET_INTERNALNAME "
        "QMAKE_TARGET_COMMENTS QMAKE_TARGET_TRADEMARKS QMAKE_MANIFEST QMAKE_TVOS_DEPLOYMENT_TARGET QMAKE_UIC_FLAGS "
        "QMAKE_WATCHOS_DEPLOYMENT_TARGET QML_IMPORT_MAJOR_VERSION QML_IMPORT_MINOR_VERSION QML_IMPORT_VERSION "
        "QML_IMPORT_NAME QML_FOREIGN_METATYPES QT QTPLUGIN QT_VERSION QT_MAJOR_VERSION QT_MINOR_VERSION "
        "QT_PATCH_VERSION RC_FILE RC_CODEPAGE RC_DEFINES RC_ICONS RC_LANG RC_INCLUDEPATH RCC_DIR REQUIRES "
        "RESOURCES RES_FILE SOURCES SUBDIRS TARGET TARGET_EXT TEMPLATE TRANSLATIONS "
        "TR_EXCLUDE UI_DIR VERSION VERSION_PE_HEADER VER_MAJ VER_MIN VER_PAT VPATH WINDOWS_TARGET_PLATFORM_VERSION "
        "WINDOWS_TARGET_PLATFORM_MIN_VERSION YACCSOURCES _PRO_FILE_ _PRO_FILE_PWD_ "
        
        "macx unix win32 "
        
        // Built-in Replace Functions
        "absolute_path basename cat clean_path dirname enumerate_vars escape_expand find files first "
        "format_number fromfile getenv join last list lower member num_add prompt quote re_escape read_registry "
        "relative_path replace resolve_depends reverse section shadowed shell_path shell_quote size sort_depends "
        "sorted split sprintf str_member str_size system system_path system_quote take_first take_last unique upper val_escape "
        
        // Built-in Test Functions
        "cache CONFIG contains count debug defined equals error eval exists export for greaterThan if "
        "include infile isActiveConfig isEmpty isEqual lessThan load log message mkpath requires system "
        "touch unset versionAtLeast versionAtMost warning write_file "
        
        //Test Function Library
        "packagesExist prepareRecursiveTarget qtCompileTest qtHaveModule";

    return nullptr;
}
